TRAINING_DATA = [
    ("fix the critical login bug", 1),
    ("we need to fix the login issue", 1),
    ("update the API documentation", 1),
    ("we should update the docs before release", 1),
    ("write unit tests for the payment module", 1),
    ("someone should design the onboarding screens", 1),
    ("optimize the database performance", 1),
    ("we need to deploy the new build", 1),
    ("please review the pull request", 1),
    ("can you implement the search feature", 1),
    ("we need someone to refactor the auth module", 1),
    ("build the new dashboard", 1),
    ("test the checkout flow", 1),
    ("resolve the memory leak issue", 1),
    ("configure the staging environment", 1),
    ("migrate the old database to new schema", 1),
    ("we should improve the app loading speed", 1),
    ("create unit tests for the user module", 1),
    ("debug the payment gateway error", 1),
    ("we need to integrate the third party api", 1),
    ("develop the notification feature", 1),
    ("we should clean up the old code", 1),
    ("prepare the release notes", 1),
    ("someone needs to handle the customer complaints", 1),
    ("we need to add error handling to the api", 1),
    ("please investigate the crash reports", 1),
    ("we should analyze the user feedback", 1),
    ("deploy the hotfix to production", 1),
    ("we need to upgrade the dependencies", 1),
    ("write documentation for the new endpoints", 1),
    ("someone should review the security audit", 1),
    ("we need to implement dark mode", 1),
    ("fix the broken navigation links", 1),
    ("we should set up monitoring alerts", 1),
    ("create the admin panel", 1),
    ("we need to optimize the image loading", 1),
    ("please update the user interface", 1),
    ("we should rebuild the search index", 1),
    ("test the new payment integration", 1),
    ("we need to document the deployment process", 1),
    ("someone should design the email templates", 1),
    ("we need to fix the session timeout bug", 1),
    ("please improve the error messages", 1),
    ("we should add pagination to the list", 1),
    ("configure the load balancer", 1),
    ("we need to write integration tests", 1),
    ("please handle the edge cases in checkout", 1),
    ("we should launch the beta version", 1),
    ("someone needs to update the privacy policy", 1),
    ("we need to install the new ssl certificate", 1),
    ("fix the responsive layout on mobile", 1),
    ("we should implement caching for the api", 1),
    ("please create the onboarding flow", 1),
    ("we need to merge the feature branch", 1),
    ("someone should approve the design mockups", 1),
    ("we need to schedule the deployment", 1),
    ("please connect the frontend to the backend", 1),
    ("we should generate the monthly report", 1),
    ("fix the data validation errors", 1),
    ("we need to manage the user permissions", 1),
    ("hi everyone lets discuss this weeks priorities", 0),
    ("this needs to be done by tomorrow", 0),
    ("it is blocking users", 0),
    ("this can wait until next monday", 0),
    ("this is high priority", 0),
    ("it is affecting the user experience", 0),
    ("so lets plan this for wednesday", 0),
    ("you are good with backend optimization right", 0),
    ("didnt you work on ui designs last month", 0),
    ("this depends on the login bug fix", 0),
    ("we should tackle this by end of week", 0),
    ("good morning everyone", 0),
    ("lets get started with the meeting", 0),
    ("any updates from last week", 0),
    ("thanks everyone for joining", 0),
    ("that sounds good to me", 0),
    ("i agree with that approach", 0),
    ("lets move on to the next topic", 0),
    ("does anyone have questions", 0),
    ("great work on the last sprint", 0),
    ("the deadline is next friday", 0),
    ("this is a blocker for the release", 0),
    ("the bug was reported yesterday", 0),
    ("users are complaining about this", 0),
    ("this is critical for the launch", 0),
    ("the performance is really slow", 0),
    ("it depends on the other task", 0),
    ("once that is done we can proceed", 0),
    ("after the fix is merged", 0),
    ("the release is on friday", 0),
    ("this sprint ends on monday", 0),
    ("the team is working on it", 0),
    ("we discussed this last week", 0),
    ("the client wants this by friday", 0),
    ("this is a known issue", 0),
    ("the fix is already in progress", 0),
    ("we will revisit this next sprint", 0),
    ("the design is pending approval", 0),
    ("this was mentioned in the last meeting", 0),
    ("the server is down right now", 0),
]
